# bazarr-alpine: minimal Bazarr image built on Alpine
#
# Strategy: pull the official Bazarr release zip (which ships vendored
# Python deps under libs/) and run it on python:alpine. Avoids pulling
# in a full Ubuntu/S6 stack like linuxserver/bazarr.
ARG BAZARR_VERSION=v1.5.6

FROM python:3.12-alpine

ARG BAZARR_VERSION

ENV PUID=13001 \
    PGID=13000 \
    TZ=America/New_York

# Runtime deps:
#   - ffmpeg: subtitle conversion (optional but commonly used)
#   - tzdata: timezone support
#   - unzip / curl: bootstrap only (removed at end of layer)
# NOTE: unrar omitted — not packaged in Alpine main due to licensing.
#       Bazarr only needs it for .rar-archived subtitle providers.
RUN apk add --no-cache \
        ffmpeg \
        7zip \
        tzdata \
        ca-certificates \
        py3-lxml \
    && apk add --no-cache --virtual .build-deps curl unzip \
    && addgroup -g 13000 bazarr \
    && adduser -D -u 13001 -G bazarr bazarr \
    && mkdir -p /app /config /media \
    && curl -fsSL "https://github.com/morpheus65535/bazarr/releases/download/${BAZARR_VERSION}/bazarr.zip" -o /tmp/bazarr.zip \
    && unzip -q /tmp/bazarr.zip -d /app \
    && rm /tmp/bazarr.zip \
    # bazarr.zip ships pure-Python deps under libs/, but C-extension packages
    # require host-specific binaries. requirements.txt declares exactly:
    #   Pillow, numpy, lxml, webrtcvad-wheels (lxml comes from apk above).
    # --no-compile skips bytecode generation; we strip __pycache__ next anyway.
    && pip install --no-cache-dir --no-compile --root-user-action=ignore \
         Pillow \
         numpy \
         webrtcvad-wheels \
    # Strip every __pycache__ from /app and site-packages — these get
    # regenerated by Python at first import and saved in /config/.cache,
    # so they're pure dead weight in the image.
    && find /app /usr/local/lib/python3.12 -type d -name __pycache__ -prune -exec rm -rf {} + \
    # Strip tests, docs, and example bundles that ship with vendored libs.
    && find /app/libs -type d \( -name tests -o -name test -o -name examples -o -name docs \) -prune -exec rm -rf {} + 2>/dev/null || true \
    && chown -R bazarr:bazarr /app /config /media \
    && apk del .build-deps

USER bazarr
WORKDIR /app

EXPOSE 6767

CMD ["python", "/app/bazarr.py", "--no-update", "--config", "/config"]
